steps:
# 1. Budowanie obrazu za pomocą Dockerfile
- name: 'gcr.io/cloud-builders/docker' # Użyjemy buildera Dockera
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ar-widget-api:$COMMIT_SHA', '.' ]

# 2. Przesłanie obrazu do Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/ar-widget-api:$COMMIT_SHA' ]

# 3. Wdrożenie na Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'ar-widget-api'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ar-widget-api:$COMMIT_SHA'
  - '--region'
  - 'europe-central2'
  - '--allow-unauthenticated'
  - '--platform'
  - 'managed'

images:
- 'gcr.io/$PROJECT_ID/ar-widget-api:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
